/** Canonical IDs for raycast regions — keep in sync with `AnatomyModel` meshes */
export const BODY_REGION_IDS = [
  "general",
  "scalp",
  "face",
  "neck",
  "thyroid",
  "shoulder_l",
  "shoulder_r",
  "upper_arm_l",
  "upper_arm_r",
  "elbow_l",
  "elbow_r",
  "forearm_l",
  "forearm_r",
  "wrist_l",
  "wrist_r",
  "hand_l",
  "hand_r",
  "chest",
  "breast_l",
  "breast_r",
  "ribs_l",
  "ribs_r",
  "upper_abdomen",
  "flank_l",
  "flank_r",
  "lower_abdomen",
  "groin",
  "pelvis",
  "hip_l",
  "hip_r",
  "upper_back",
  "mid_back",
  "lower_back",
  "buttock_l",
  "buttock_r",
  "thigh_l",
  "thigh_r",
  "knee_l",
  "knee_r",
  "shin_l",
  "shin_r",
  "ankle_l",
  "ankle_r",
  "foot_l",
  "foot_r",
  "lung_l",
  "lung_r",
  "heart",
  "liver",
  "stomach",
  "intestines",
  "kidney_l",
  "kidney_r",
] as const;

export type BodyRegionId = (typeof BODY_REGION_IDS)[number];

export type BodyView = "front" | "back";
export type BodyLayer = "external" | "internal";

export type BodyRegionMeta = {
  id: BodyRegionId;
  label: string;
  views: BodyView[];
  layer: BodyLayer;
};

export const BODY_REGION_META: Record<BodyRegionId, BodyRegionMeta> = {
  general: { id: "general", label: "General / unspecified", views: ["front", "back"], layer: "external" },
  scalp: { id: "scalp", label: "Scalp", views: ["front", "back"], layer: "external" },
  face: { id: "face", label: "Face", views: ["front"], layer: "external" },
  neck: { id: "neck", label: "Neck", views: ["front", "back"], layer: "external" },
  thyroid: { id: "thyroid", label: "Thyroid area", views: ["front"], layer: "internal" },
  shoulder_l: { id: "shoulder_l", label: "Left shoulder", views: ["front", "back"], layer: "external" },
  shoulder_r: { id: "shoulder_r", label: "Right shoulder", views: ["front", "back"], layer: "external" },
  upper_arm_l: { id: "upper_arm_l", label: "Left upper arm", views: ["front", "back"], layer: "external" },
  upper_arm_r: { id: "upper_arm_r", label: "Right upper arm", views: ["front", "back"], layer: "external" },
  elbow_l: { id: "elbow_l", label: "Left elbow", views: ["front", "back"], layer: "external" },
  elbow_r: { id: "elbow_r", label: "Right elbow", views: ["front", "back"], layer: "external" },
  forearm_l: { id: "forearm_l", label: "Left forearm", views: ["front", "back"], layer: "external" },
  forearm_r: { id: "forearm_r", label: "Right forearm", views: ["front", "back"], layer: "external" },
  wrist_l: { id: "wrist_l", label: "Left wrist", views: ["front", "back"], layer: "external" },
  wrist_r: { id: "wrist_r", label: "Right wrist", views: ["front", "back"], layer: "external" },
  hand_l: { id: "hand_l", label: "Left hand", views: ["front", "back"], layer: "external" },
  hand_r: { id: "hand_r", label: "Right hand", views: ["front", "back"], layer: "external" },
  chest: { id: "chest", label: "Chest / sternum", views: ["front", "back"], layer: "external" },
  breast_l: { id: "breast_l", label: "Left chest wall", views: ["front"], layer: "external" },
  breast_r: { id: "breast_r", label: "Right chest wall", views: ["front"], layer: "external" },
  ribs_l: { id: "ribs_l", label: "Left ribs", views: ["front", "back"], layer: "external" },
  ribs_r: { id: "ribs_r", label: "Right ribs", views: ["front", "back"], layer: "external" },
  upper_abdomen: { id: "upper_abdomen", label: "Upper abdomen", views: ["front", "back"], layer: "external" },
  flank_l: { id: "flank_l", label: "Left flank", views: ["front", "back"], layer: "external" },
  flank_r: { id: "flank_r", label: "Right flank", views: ["front", "back"], layer: "external" },
  lower_abdomen: { id: "lower_abdomen", label: "Lower abdomen", views: ["front", "back"], layer: "external" },
  groin: { id: "groin", label: "Groin", views: ["front"], layer: "external" },
  pelvis: { id: "pelvis", label: "Pelvis", views: ["front", "back"], layer: "external" },
  hip_l: { id: "hip_l", label: "Left hip", views: ["front", "back"], layer: "external" },
  hip_r: { id: "hip_r", label: "Right hip", views: ["front", "back"], layer: "external" },
  upper_back: { id: "upper_back", label: "Upper back", views: ["back"], layer: "external" },
  mid_back: { id: "mid_back", label: "Mid back", views: ["back"], layer: "external" },
  lower_back: { id: "lower_back", label: "Lower back", views: ["back"], layer: "external" },
  buttock_l: { id: "buttock_l", label: "Left buttock", views: ["back"], layer: "external" },
  buttock_r: { id: "buttock_r", label: "Right buttock", views: ["back"], layer: "external" },
  thigh_l: { id: "thigh_l", label: "Left thigh", views: ["front", "back"], layer: "external" },
  thigh_r: { id: "thigh_r", label: "Right thigh", views: ["front", "back"], layer: "external" },
  knee_l: { id: "knee_l", label: "Left knee", views: ["front", "back"], layer: "external" },
  knee_r: { id: "knee_r", label: "Right knee", views: ["front", "back"], layer: "external" },
  shin_l: { id: "shin_l", label: "Left shin", views: ["front", "back"], layer: "external" },
  shin_r: { id: "shin_r", label: "Right shin", views: ["front", "back"], layer: "external" },
  ankle_l: { id: "ankle_l", label: "Left ankle", views: ["front", "back"], layer: "external" },
  ankle_r: { id: "ankle_r", label: "Right ankle", views: ["front", "back"], layer: "external" },
  foot_l: { id: "foot_l", label: "Left foot", views: ["front", "back"], layer: "external" },
  foot_r: { id: "foot_r", label: "Right foot", views: ["front", "back"], layer: "external" },
  lung_l: { id: "lung_l", label: "Left lung (concept)", views: ["front", "back"], layer: "internal" },
  lung_r: { id: "lung_r", label: "Right lung (concept)", views: ["front", "back"], layer: "internal" },
  heart: { id: "heart", label: "Heart region", views: ["front"], layer: "internal" },
  liver: { id: "liver", label: "Liver region", views: ["front", "back"], layer: "internal" },
  stomach: { id: "stomach", label: "Stomach region", views: ["front"], layer: "internal" },
  intestines: { id: "intestines", label: "Intestines", views: ["front"], layer: "internal" },
  kidney_l: { id: "kidney_l", label: "Left kidney region", views: ["back"], layer: "internal" },
  kidney_r: { id: "kidney_r", label: "Right kidney region", views: ["back"], layer: "internal" },
};

export type RegionMeshDef = {
  id: BodyRegionId;
  position: [number, number, number];
  args: [number, number, number];
  rotation?: [number, number, number];
};

/** Low-poly box layout in model space (Y up) — front faces +Z */
export const REGION_MESH_DEFS: RegionMeshDef[] = [
  { id: "scalp", position: [0, 1.62, 0.12], args: [0.34, 0.14, 0.28] },
  { id: "face", position: [0, 1.42, 0.14], args: [0.22, 0.22, 0.18] },
  { id: "neck", position: [0, 1.22, 0.08], args: [0.16, 0.18, 0.16] },
  { id: "thyroid", position: [0, 1.18, 0.11], args: [0.12, 0.08, 0.1] },
  { id: "shoulder_l", position: [-0.28, 1.28, 0.04], args: [0.16, 0.12, 0.2] },
  { id: "shoulder_r", position: [0.28, 1.28, 0.04], args: [0.16, 0.12, 0.2] },
  { id: "upper_arm_l", position: [-0.32, 1.02, 0.02], args: [0.12, 0.28, 0.12] },
  { id: "upper_arm_r", position: [0.32, 1.02, 0.02], args: [0.12, 0.28, 0.12] },
  { id: "elbow_l", position: [-0.32, 0.78, 0.02], args: [0.1, 0.1, 0.1] },
  { id: "elbow_r", position: [0.32, 0.78, 0.02], args: [0.1, 0.1, 0.1] },
  { id: "forearm_l", position: [-0.32, 0.56, 0.04], args: [0.1, 0.32, 0.1] },
  { id: "forearm_r", position: [0.32, 0.56, 0.04], args: [0.1, 0.32, 0.1] },
  { id: "wrist_l", position: [-0.32, 0.34, 0.06], args: [0.08, 0.06, 0.08] },
  { id: "wrist_r", position: [0.32, 0.34, 0.06], args: [0.08, 0.06, 0.08] },
  { id: "hand_l", position: [-0.32, 0.2, 0.08], args: [0.1, 0.12, 0.08] },
  { id: "hand_r", position: [0.32, 0.2, 0.08], args: [0.1, 0.12, 0.08] },
  { id: "chest", position: [0, 1.12, 0.12], args: [0.42, 0.22, 0.2] },
  { id: "breast_l", position: [-0.12, 1.05, 0.14], args: [0.14, 0.12, 0.12] },
  { id: "breast_r", position: [0.12, 1.05, 0.14], args: [0.14, 0.12, 0.12] },
  { id: "ribs_l", position: [-0.22, 1.0, 0.1], args: [0.12, 0.2, 0.16] },
  { id: "ribs_r", position: [0.22, 1.0, 0.1], args: [0.12, 0.2, 0.16] },
  { id: "upper_abdomen", position: [0, 0.88, 0.1], args: [0.36, 0.18, 0.18] },
  { id: "flank_l", position: [-0.22, 0.82, 0.06], args: [0.1, 0.2, 0.14] },
  { id: "flank_r", position: [0.22, 0.82, 0.06], args: [0.1, 0.2, 0.14] },
  { id: "lower_abdomen", position: [0, 0.66, 0.1], args: [0.34, 0.16, 0.16] },
  { id: "groin", position: [0, 0.52, 0.1], args: [0.2, 0.1, 0.12] },
  { id: "pelvis", position: [0, 0.58, -0.02], args: [0.32, 0.12, 0.18] },
  { id: "hip_l", position: [-0.18, 0.56, 0], args: [0.14, 0.12, 0.16] },
  { id: "hip_r", position: [0.18, 0.56, 0], args: [0.14, 0.12, 0.16] },
  { id: "upper_back", position: [0, 1.18, -0.12], args: [0.4, 0.2, 0.14] },
  { id: "mid_back", position: [0, 0.98, -0.12], args: [0.38, 0.2, 0.14] },
  { id: "lower_back", position: [0, 0.76, -0.12], args: [0.34, 0.16, 0.14] },
  { id: "buttock_l", position: [-0.14, 0.62, -0.16], args: [0.16, 0.12, 0.14] },
  { id: "buttock_r", position: [0.14, 0.62, -0.16], args: [0.16, 0.12, 0.14] },
  { id: "thigh_l", position: [-0.14, 0.38, 0.02], args: [0.16, 0.36, 0.14] },
  { id: "thigh_r", position: [0.14, 0.38, 0.02], args: [0.16, 0.36, 0.14] },
  { id: "knee_l", position: [-0.14, 0.12, 0.04], args: [0.12, 0.12, 0.12] },
  { id: "knee_r", position: [0.14, 0.12, 0.04], args: [0.12, 0.12, 0.12] },
  { id: "shin_l", position: [-0.14, -0.12, 0.04], args: [0.1, 0.32, 0.1] },
  { id: "shin_r", position: [0.14, -0.12, 0.04], args: [0.1, 0.32, 0.1] },
  { id: "ankle_l", position: [-0.14, -0.34, 0.06], args: [0.08, 0.08, 0.1] },
  { id: "ankle_r", position: [0.14, -0.34, 0.06], args: [0.08, 0.08, 0.1] },
  { id: "foot_l", position: [-0.14, -0.46, 0.1], args: [0.1, 0.06, 0.2] },
  { id: "foot_r", position: [0.14, -0.46, 0.1], args: [0.1, 0.06, 0.2] },
  { id: "lung_l", position: [-0.14, 1.1, 0.06], args: [0.16, 0.2, 0.22], rotation: [0, 0, 0] },
  { id: "lung_r", position: [0.14, 1.1, 0.06], args: [0.16, 0.2, 0.22] },
  { id: "heart", position: [0.02, 1.08, 0.08], args: [0.12, 0.12, 0.12] },
  { id: "liver", position: [0.12, 0.86, 0.06], args: [0.18, 0.14, 0.16] },
  { id: "stomach", position: [-0.06, 0.84, 0.08], args: [0.2, 0.14, 0.14] },
  { id: "intestines", position: [0, 0.68, 0.04], args: [0.26, 0.14, 0.18] },
  { id: "kidney_l", position: [-0.16, 0.88, -0.08], args: [0.1, 0.14, 0.08] },
  { id: "kidney_r", position: [0.16, 0.88, -0.08], args: [0.1, 0.14, 0.08] },
];
